//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2019.04.02 at 08:11:49 PM MSK
//


package by.tolkun.xmlparser.entity.medicine;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Currency.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Currency">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BYN"/>
 *     &lt;enumeration value="EUR"/>
 *     &lt;enumeration value="USD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 * @author Kirill Tolkun
 */
@XmlType(name = "Currency")
@XmlEnum
public enum Currency {

    /**
     * Belorussian currency.
     */
    BYN,
    /**
     * Europe currency.
     */
    EUR,
    /**
     * USA currency.
     */
    USD;

    /**
     * Form {@code Currency} from {@code v}.
     *
     * @param v the string to create enum
     * @return object of {@code Currency}
     */
    public static Currency fromValue(final String v) {
        return valueOf(v);
    }

    /**
     * Get value of enum.
     *
     * @return name of enum element
     */
    public String value() {
        return name();
    }

}
