//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2019.04.02 at 08:11:49 PM MSK
//


package by.tolkun.xmlparser.entity.medicine;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.Objects;


/**
 * <p>Java class for Dosage complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType name="Dosage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="size"
 *         type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="period"
 *         type="{http://www.tolkun.by/xmlparser}Period"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 * @author Kirill Tolkun
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dosage", propOrder = {

})
public class Dosage {

    /**
     * Logger of class {@code Dosage}.
     */
    private static final Logger LOGGER
            = LogManager.getLogger(Double.class);

    /**
     * Size of dosage.
     */
    private int size;
    /**
     * Period of repeated medication.
     */
    @XmlElement(required = true)
    private Period period;

    /**
     * Default constructor.
     */
    public Dosage() {
        LOGGER.debug("Dosage created.");
    }

    /**
     * Gets the value of the size property.
     *
     * @return size of dosage
     */
    public int getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     *
     * @param value of dosage
     */
    public void setSize(final int value) {
        this.size = value;
    }

    /**
     * Gets the value of the period property.
     *
     * @return possible object is
     * {@link Period }
     */
    public Period getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     *
     * @param value allowed object is
     *              {@link Period }
     */
    public void setPeriod(final Period value) {
        this.period = value;
    }

    /**
     * Compares this object to the specified object. The result is
     * {@code true} if the argument is not
     * {@code null} and is an {@code Dosage} object that
     * contains the same field values.
     *
     * @param o the object to compare with.
     * @return {@code true} if the objects are the same;
     * {@code false} otherwise.
     */
    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Dosage dosage = (Dosage) o;
        return size == dosage.size
                && Objects.equals(period, dosage.period);
    }

    /**
     * Returns a hash code for a {@code Dosage}.
     *
     * @return a hash code value for a {@code Dosage}.
     */
    @Override
    public int hashCode() {
        return Objects.hash(size, period);
    }

    /**
     * Returns a {@code String} object representing this
     * {@code Dosage}.
     *
     * @return a string representation of the information of this
     * object
     */
    @Override
    public String toString() {
        return "Dosage{"
                + "size=" + size
                + ", period=" + period
                + '}';
    }
}
