//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2019.04.02 at 08:11:49 PM MSK
//


package by.tolkun.xmlparser.entity.medicine;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Group.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Group">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="vaccines"/>
 *     &lt;enumeration value="antibiotics"/>
 *     &lt;enumeration value="antiseptics"/>
 *     &lt;enumeration value="antiviral"/>
 *     &lt;enumeration value="antidepressants"/>
 *     &lt;enumeration value="neuroleptics"/>
 *     &lt;enumeration value="nootropes"/>
 *     &lt;enumeration value="sedatives"/>
 *     &lt;enumeration value="sleeping pills"/>
 *     &lt;enumeration value="painkillers"/>
 *     &lt;enumeration value="vitamins"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 * @author Kirill Tolkun
 */
@XmlType(name = "Group")
@XmlEnum
public enum Group {

    /**
     * Group of vaccines.
     */
    @XmlEnumValue("vaccines")
    VACCINES("vaccines"),
    /**
     * Group of antibiotics.
     */
    @XmlEnumValue("antibiotics")
    ANTIBIOTICS("antibiotics"),
    /**
     * Group of antiseptics.
     */
    @XmlEnumValue("antiseptics")
    ANTISEPTICS("antiseptics"),
    /**
     * Group of antiviral.
     */
    @XmlEnumValue("antiviral")
    ANTIVIRAL("antiviral"),
    /**
     * Group of antidepressants.
     */
    @XmlEnumValue("antidepressants")
    ANTIDEPRESSANTS("antidepressants"),
    /**
     * Group of neuroleptics.
     */
    @XmlEnumValue("neuroleptics")
    NEUROLEPTICS("neuroleptics"),
    /**
     * Group of nootropes.
     */
    @XmlEnumValue("nootropes")
    NOOTROPES("nootropes"),
    /**
     * Group of sedatives.
     */
    @XmlEnumValue("sedatives")
    SEDATIVES("sedatives"),
    /**
     * Group of sleeping pills.
     */
    @XmlEnumValue("sleeping pills")
    SLEEPING_PILLS("sleeping pills"),
    /**
     * Group of painkillers.
     */
    @XmlEnumValue("painkillers")
    PAINKILLERS("painkillers"),
    /**
     * Group of vitamins.
     */
    @XmlEnumValue("vitamins")
    VITAMINS("vitamins");
    /**
     * Value of group.
     */
    private final String value;

    /**
     * Constructor with parameters.
     *
     * @param v the string to create {@code Group}
     */
    Group(final String v) {
        value = v;
    }

    /**
     * Form {@code Group} from {@code v}.
     *
     * @param v the string to create enum
     * @return object of {@code Group}
     */
    public static Group fromValue(final String v) {
        for (Group c : Group.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    /**
     * Get value of enum.
     *
     * @return name of enum element
     */
    public String value() {
        return value;
    }

}
