//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2019.04.02 at 08:11:49 PM MSK
//


package by.tolkun.xmlparser.entity.medicine;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * <p>Java class for Versions complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType name="Versions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version"
 *         type="{http://www.tolkun.by/xmlparser}Version"
 *         maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 * @author Kirill Tolkun
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Versions", propOrder = {
        "version"
})
public class Versions {

    /**
     * Logger of class {@code Versions}.
     */
    private static final Logger LOGGER
            = LogManager.getLogger(Versions.class);

    /**
     * List of versions.
     */
    @XmlElement(required = true)
    private List<Version> version;

    /**
     * Default constructor.
     */
    public Versions() {
        LOGGER.debug("Versions created.");
    }

    /**
     * Gets the value of the version property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the version
     * property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVersion().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Version }
     *
     * @return version of medicine
     */
    public List<Version> getVersion() {
        if (version == null) {
            version = new ArrayList<Version>();
        }
        return this.version;
    }

    /**
     * Get number of companies in the version.
     *
     * @return number of companies
     */
    public int getCompanyNumber() {
        return version
                .stream()
                .mapToInt(value ->
                        value.getCompanyOrCompanyCertificate().size()
                )
                .sum();
    }

    /**
     * Compares this object to the specified object. The result is
     * {@code true} if the argument is not
     * {@code null} and is an {@code Versions} object that
     * contains the same field values.
     *
     * @param o the object to compare with.
     * @return {@code true} if the objects are the same;
     * {@code false} otherwise.
     */
    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Versions versions = (Versions) o;
        return Objects.equals(version, versions.version);
    }

    /**
     * Returns a hash code for a {@code Versions}.
     *
     * @return a hash code value for a {@code Versions}.
     */
    @Override
    public int hashCode() {
        return Objects.hash(version);
    }

    /**
     * Returns a {@code String} object representing this
     * {@code Versions}.
     *
     * @return a string representation of the information of this
     * object
     */
    @Override
    public String toString() {
        return "Versions{"
                + "version=" + version
                + '}';
    }
}
