//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2019.04.02 at 08:11:49 PM MSK
//


package by.tolkun.xmlparser.entity.medicine;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * <p>Java class for Version complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType name="Version">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="company"
 *         type="{http://www.tolkun.by/xmlparser}Company"/>
 *         &lt;element name="company-certificate"
 *         type="{http://www.tolkun.by/xmlparser}CertificateCompany"/>
 *       &lt;/choice>
 *       &lt;attribute name="type" use="required"
 *       type="{http://www.tolkun.by/xmlparser}VersionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 * @author Kirill Tolkun
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Version", propOrder = {
        "companyOrCompanyCertificate"
})
public class Version {

    /**
     * Logger of class {@code Versions}.
     */
    private static final Logger LOGGER
            = LogManager.getLogger(Version.class);

    /**
     * List of companies.
     */
    @XmlElements({
            @XmlElement(name = "company",
                    type = Company.class),
            @XmlElement(name = "company-certificate",
                    type = CertificateCompany.class)
    })
    private List<Company> companyOrCompanyCertificate;
    /**
     * Type of version.
     */
    @XmlAttribute(name = "type", required = true)
    private VersionType type;

    /**
     * Default constructor.
     */
    public Version() {
        LOGGER.debug("Version created.");
    }

    /**
     * Gets the value of the companyOrCompanyCertificate property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the
     * companyOrCompanyCertificate property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompanyOrCompanyCertificate().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Company }
     * {@link CertificateCompany }
     *
     * @return list companies
     */
    public List<Company> getCompanyOrCompanyCertificate() {
        if (companyOrCompanyCertificate == null) {
            companyOrCompanyCertificate = new ArrayList<Company>();
        }
        return this.companyOrCompanyCertificate;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link VersionType }
     */
    public VersionType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link VersionType }
     */
    public void setType(final VersionType value) {
        this.type = value;
    }

    /**
     * Compares this object to the specified object. The result is
     * {@code true} if the argument is not
     * {@code null} and is an {@code Version} object that
     * contains the same field values.
     *
     * @param o the object to compare with.
     * @return {@code true} if the objects are the same;
     * {@code false} otherwise.
     */
    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Version version = (Version) o;
        return Objects.equals(companyOrCompanyCertificate,
                version.companyOrCompanyCertificate)
                && type == version.type;
    }

    /**
     * Returns a hash code for a {@code Version}.
     *
     * @return a hash code value for a {@code Version}.
     */
    @Override
    public int hashCode() {
        return Objects.hash(companyOrCompanyCertificate, type);
    }

    /**
     * Returns a {@code String} object representing this
     * {@code Version}.
     *
     * @return a string representation of the information of this
     * object
     */
    @Override
    public String toString() {
        return "Version{"
                + "companyOrCompanyCertificate=" + companyOrCompanyCertificate
                + ", type=" + type
                + '}';
    }
}
